name: ompi-4.0

on:
  push:
    branches:
      - master
    paths:
      - 'cas/ompi-4.0.Dockerfile'
  pull_request:
    branches: 
      - master
    paths:
      - 'cas/ompi-4.0.Dockerfile'

env:
  BASE_IMAGE_NAME: ompi-4.0

  DOCKERHUB_REPO: hpc-base-container
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build image
        run: docker build . --file "cas/ompi-4.0.Dockerfile" --tag $BASE_IMAGE_NAME

  deploy:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file "cas/ompi-4.0.Dockerfile" --tag $BASE_IMAGE_NAME

      - name: Log into registry
        run: echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USER --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$DOCKERHUB_USER/$DOCKERHUB_REPO
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$BASE_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BASE_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
